[SWT-41] Drop System.Drawing.Common library and .NET Framework 4.5.1
PyramidTechnologies/ThermalTalk pull request #21
Opened 2023-10-18 18:14 UTC by CrDoming

[[SWT-41](https://pyramid.atlassian.net/browse/SWT-41)]

The `SkiaSharp` library has replaced the `System.Drawing` library so UWP apps can utilize `ThermalTalk`. Since `SkiaSharp` does not support .NET Framework 4.5.1, that framework was dropped. Additionally, the 3 sample apps were combined into 1 command-line interface.

[SWT-41]: https://pyramid.atlassian.net/browse/SWT-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-10-18 19:12 UTC, codygillespie commented
@CrDoming I am running into an issue with barcode printing via the CLI.

Command used: 
`printcode phoenix COM14 ABCDEF`

Print I am seeing: 
![image](https://github.com/PyramidTechnologies/ThermalTalk/assets/61803875/70ad6027-7f4e-48e4-9591-476c6d508e58)

2023-10-18 20:08 UTC, codygillespie commented
> > @CrDoming I am running into an issue with barcode printing via the CLI.
> > Command used: `printcode phoenix COM14 ABCDEF`
> > Print I am seeing: ![image](https://user-images.githubusercontent.com/61803875/276373366-70ad6027-7f4e-48e4-9591-476c6d508e58.png)
> 
> Is the firmware on your Phoenix printer version 1.9 or newer?

This was on Phoenix 1.08 UNV firmware

2023-10-18 20:11 UTC, CrDoming commented
@codygillespie 

Printing a raster image is only supported on Phoenix firmware versions 1.9 and newer, according to https://escpos.readthedocs.io/en/latest/imaging.html.

2023-10-18 22:04 UTC, codygillespie requested changes

2023-10-18 22:04 UTC, codygillespie commented on ThermalTalk/ThermalTalk.csproj
>      <Version>2.1.1.0</Version>
Let's move to v3

2023-10-18 22:04 UTC, codygillespie commented on ThermalTalk/ThermalTalk.csproj
>      <Version>2.1.1.0</Version>
And lets add a section about v3 in the readme as well as a statement on what .NET framework users should do in order to use thermaltalk (i.e. use v2)

2023-10-20 22:13 UTC, codygillespie approved these changes

2023-10-20 22:13 UTC, merged